# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20151217_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='areaConstruida',
            new_name='area_Construida',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='vagasGaragem',
            new_name='vagas_Garagem',
        ),
    ]
