# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20151217_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='areaTotal',
            new_name='area_total',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='vagas_Garagem',
            new_name='vagas_garagem',
        ),
    ]
