# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20151217_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='area_Construida',
            new_name='area_construida',
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_negociacao',
            field=models.CharField(choices=[(0, b'Aluguel'), (1, b'Venda')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
