# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20151219_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='foto_1',
            field=models.FileField(null=True, upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
