# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_imovel_foto_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='foto_2',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto_3',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto_4',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto_5',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto_6',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto_7',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto_8',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_1',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
