# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20151219_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='logradouro',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_4',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_5',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_6',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_7',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='foto_8',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.sample_upload_to_function),
        ),
    ]
