# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='banheiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas_garagem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
