# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:04
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('portal', '0011_auto_20160107_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='destaque',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AuthorUser'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.AuthorUser'),
        ),
    ]
