# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20160107_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
