# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20160107_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='author',
            new_name='usuario',
        ),
    ]
