# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0016_auto_20160107_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destaque',
            name='author',
        ),
        migrations.AddField(
            model_name='destaque',
            name='usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
