# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20160107_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cpf', models.TextField()),
                ('rg', models.TextField()),
                ('telefone_fixo', models.TextField()),
                ('celular', models.TextField()),
                ('email', models.TextField()),
                ('telefone_comercial', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Proprietario'),
        ),
    ]
