# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_proprietario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietario',
            old_name='celular',
            new_name='celular_1',
        ),
        migrations.AddField(
            model_name='proprietario',
            name='celular_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
