# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20160107_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='celular_1',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='celular_2',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='rg',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='telefone_comercial',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='telefone_fixo',
            field=models.CharField(max_length=13),
        ),
    ]
