# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20160107_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Proprietario'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='celular_1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='celular_2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='telefone_comercial',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
