# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20160107_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='data_divulgacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
