# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20160107_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='foto_1',
            field=models.ImageField(upload_to=portal.models.sample_upload_to_function),
        ),
    ]
