<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.2.310
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Cadastro de imóvel envio',
	'heading' => 'Envio de novo formulário',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcado',
		'checkbox_unchecked' => 'Desmarcado',
		'submitted_from' => 'Formulário enviado do site: %s',
		'submitted_by' => 'Endereço IP do visitante: %s',
		'too_many_submissions' => 'Muitos envios recentes deste IP',
		'failed_to_send_email' => 'Falha no envio do email',
		'invalid_reCAPTCHA_private_key' => 'Chave privada do reCAPTCHA inválida.',
		'invalid_field_type' => 'Tipo de campo desconhecido \"%s\".',
		'invalid_form_config' => 'O campo \"%s\" possui uma configuração inválida.',
		'unknown_method' => 'Método de solicitação de servidor desconhecido'
	),
	'email' => array(
		'from' => 'atendimento@corretaimov.com.br',
		'to' => 'atendimento@corretaimov.com.br'
	),
	'fields' => array(
		'custom_U920' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nome',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Nome\" é obrigatório.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'e-mail',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"e-mail\" é obrigatório.',
				'format' => 'O campo \"e-mail\" possui um email inválido.'
			)
		),
		'custom_U944' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'RG',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"RG\" é obrigatório.'
			)
		),
		'custom_U925' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'CPF',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"CPF\" é obrigatório.'
			)
		),
		'custom_U938' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Endereço Completo',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Endereço Completo\" é obrigatório.'
			)
		),
		'custom_U933' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Cidade/Estado',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Cidade/Estado\" é obrigatório.'
			)
		),
		'custom_U912' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Telefones',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Telefones\" é obrigatório.'
			)
		),
		'custom_U1382' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Endereço',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Endereço\" é obrigatório.'
			)
		),
		'custom_U1386' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Bairro',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Bairro\" é obrigatório.'
			)
		),
		'custom_U1390' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Valor do Condomínio',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Valor do Condomínio\" é obrigatório.'
			)
		),
		'custom_U1394' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Área Total',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Área Total\" é obrigatório.'
			)
		),
		'custom_U1398' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Área Construída',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Área Construída\" é obrigatório.'
			)
		),
		'custom_U1512' => array(
			'order' => 16,
			'type' => 'string',
			'label' => 'Descreva o imóvel',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Descreva o imóvel\" é obrigatório.'
			)
		),
		'custom_U1516' => array(
			'order' => 17,
			'type' => 'string',
			'label' => 'Valor da Locação',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1520' => array(
			'order' => 18,
			'type' => 'string',
			'label' => 'Valor de Venda',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1524' => array(
			'order' => 19,
			'type' => 'string',
			'label' => 'Observações',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Observações\" é obrigatório.'
			)
		),
		'custom_U1559' => array(
			'order' => 20,
			'type' => 'checkbox',
			'label' => 'Li e concordo com os termos e condições acima descritos',
			'required' => true,
			'errors' => array(
				'required' => 'O campo \"Li e concordo com os termos e condições acima descritos\" é obrigatório.'
			)
		),
		'custom_U1402' => array(
			'order' => 15,
			'type' => 'radiogroup',
			'label' => 'Dá Financiamento?',
			'required' => true,
			'optionItems' => array(
				'Sim',
				'Não'
			),
			'errors' => array(
				'required' => 'O campo \"Dá Financiamento?\" é obrigatório.',
				'format' => 'O campo \"Dá Financiamento?\" possui um valor inválido.'
			)
		),
		'custom_U1281' => array(
			'order' => 8,
			'type' => 'radiogroup',
			'label' => 'Tipo de Negócio',
			'required' => true,
			'optionItems' => array(
				'Venda',
				'Locação'
			),
			'errors' => array(
				'required' => 'O campo \"Tipo de Negócio\" é obrigatório.',
				'format' => 'O campo \"Tipo de Negócio\" possui um valor inválido.'
			)
		),
		'custom_U1323' => array(
			'order' => 9,
			'type' => 'radiogroup',
			'label' => 'Tipo de imóvel',
			'required' => true,
			'optionItems' => array(
				'Casa',
				'Apartamento',
				'Kitinet',
				'Casa Comercial',
				'Barracão',
				'Galpão',
				'Chácara',
				'Fazenda',
				'Hotel',
				'Loja',
				'Usina',
				'Ponto Comercial',
				'Prédio',
				'Prédio Comercial'
			),
			'errors' => array(
				'required' => 'O campo \"Tipo de imóvel\" é obrigatório.',
				'format' => 'O campo \"Tipo de imóvel\" possui um valor inválido.'
			)
		)
	)
);

process_form($form);
?>
